### PR TITLE
update to 0.53-2

### PR DESCRIPTION
**Pull request by sebshader**
also took out 'test' name in .tcl file, changed big 'if/else' block to 'switch' statement

### CODE REVIEW

**Comment by porres** [comment]
Thanks for this, I still need to test in the current master, just a note, this doesn't work on Pd 0.53-2 which has been already released and I think current master is now aimed at 0.54-0 with new objects, multichannel support and all... so the PR name was misleading. In any case, just confirming that the changes seem to work on current master but, as I suspected, nothing happens with the current latest release.

Now for some questions, what did you need to change and why? Since you renamed the file I lost track of the modifications. Do you understand what has changed in the source code and why that needed to happen? I'm just asking out of curiosity.

**Comment by porres** [comment]
This is easily incorporated in the core of current pd and it works!!! One more thing, how can we have a single file? I think it would be much better

**Comment by sebshader** [comment]
The change is that we can't just modify the .popup menu at loadtime since now each menu has its own popup. Therefore we have to piggyback onto pd's proc that creates the popup using the 'trace' command, and then modify the newly created menu by getting info from trace.

(If this were in pd then this wouldn't be necessary; we could just call our proc from the same thing that already makes the menu)

I also replaced some 'if then's w/ a switch statement.

I thought it's more 'consistent' to have a regular name and leave things like 'test' for version numbers

**Comment by sebshader** [comment]
I think we could have a single file, but leaving the objects as separate might be a good pattern for future extensibility

**Comment by porres** [comment]
For this case I'd rather have a single file because I think it'll be really hard to deal with expansion anyway

**Comment by porres** [comment]
I guess i figured out how to do it in a single file

**Pull request merged**
